### PR TITLE
Implemented correction for Issue #16 TypeError

### PR DESCRIPTION
**Pull request by arashmarzi**
Using `sorted(...)` instead of `reversed(...)` as this resulted in the following error on my Raspberry Pi model A with Python 2.7.9. 

`TypeError: argument to reversed() must be a sequence`

Moved this method call to `GetMentions(...)` in TweetStreetCam.py to improve clarity.

### CODE REVIEW

**Comment by mikestreety** [comment]
Thanks for this arash - I will double check it works on my Pi and merge in.

For reference, I have python `2.7.3`

**Comment by mikestreety** [comment]
I have just noticed you deleted the `_config.cfg.skel` - ming popping it back in?

Thanks!

**Comment by mikestreety** [comment]
Have tested and all seems to work from my end - if you could check the config file back in I will merge away.

Thanks again for resolving this!

**Comment by arashmarzi** [comment]
Thanks for verifying my changes, I re-added the _config.cfg.skel file. Let me know if anything else is missing

**Pull request merged**
